coverage tag -tagname "testplan.1.1" -cvgmatch "i2c_transaction_cg"
coverage tag -tagname "testplan.1.2" -cvgmatch "i2c_transaction_cg" -cvpmatch "I2C_ADDRESS"
coverage tag -tagname "testplan.1.3" -cvgmatch "i2c_transaction_cg" -cvpmatch "I2C_DATA"
coverage tag -tagname "testplan.1.4" -cvgmatch "i2c_transaction_cg" -cvpmatch "I2C_OP"
coverage tag -tagname "testplan.1.5" -cvgmatch "i2c_transaction_cg" -crossmatch "I2C_addr_x_op"
coverage tag -tagname "testplan.2.1" -cvgmatch "wb_transaction_cg"
coverage tag -tagname "testplan.2.2" -cvgmatch "wb_transaction_cg" -cvpmatch "WB_ADDRESS"
coverage tag -tagname "testplan.2.3" -cvgmatch "wb_transaction_cg" -cvpmatch "WB_DATA"
coverage tag -tagname "testplan.2.4" -cvgmatch "wb_transaction_cg" -cvpmatch "WB_WE"
coverage tag -tagname "testplan.2.5" -cvgmatch "wb_transaction_cg" -crossmatch "WB_addr_x_we"
